/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package src;

import java.awt.Color;
import javax.swing.JButton;

/**
 *
 * @author cakpinar
 */
public class editSchForDoc extends javax.swing.JFrame {
    String connector;
    String dname;
    Operation op = new Operation();
    /**
     * Creates new form editSchForDoc
     */
    public editSchForDoc() {
        initComponents();
    }
    
    
    public void updateC(){
        setColorForButtons(m1,0);
        setColorForButtons(m2,1,2);
        setColorForButtons(m3,2,3);
        setColorForButtons(m4,3,4);
        setColorForButtons(m5,4,5);
        setColorForButtons(tu1,5,6);
        setColorForButtons(tu2,6,7);
        setColorForButtons(tu3,7,8);
        setColorForButtons(tu4,8,9);
        setColorForButtons(tu5,9,10);
        setColorForButtons(w1,10,11);
        setColorForButtons(w2,11,12);
        setColorForButtons(w3,12,13);
        setColorForButtons(w4,13,14);
        setColorForButtons(w5,14,15);
        setColorForButtons(th1,15,16);
        setColorForButtons(th2,16,17);
        setColorForButtons(th3,17,18);
        setColorForButtons(th4,18,19);
        setColorForButtons(th5,19,20);
        setColorForButtons(f1,20,21);
        setColorForButtons(f2,21,22);
        setColorForButtons(f3,22,23);
        setColorForButtons(f4,23,24);
        setColorForButtons(f5,24);
    }
    
    
    public void setColorForButtons(JButton a, int i1, int i2){
        dname = op.selectDName(this.connector);
        
        String sch = op.takeSchedule(dname);
        if(sch.substring(i1,i2).equals("1")){
            a.setBackground(Color.red);
        }
    }
    
    public void setColorForButtons(JButton a, int i1){
        dname = op.selectDName(this.connector);
        
        String sch = op.takeSchedule(dname);
        if(sch.charAt(i1)=='1'){
            a.setBackground(Color.red);
        }
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        m1 = new javax.swing.JButton();
        tu1 = new javax.swing.JButton();
        w1 = new javax.swing.JButton();
        th1 = new javax.swing.JButton();
        f1 = new javax.swing.JButton();
        m2 = new javax.swing.JButton();
        m3 = new javax.swing.JButton();
        m4 = new javax.swing.JButton();
        m5 = new javax.swing.JButton();
        tu2 = new javax.swing.JButton();
        w2 = new javax.swing.JButton();
        th2 = new javax.swing.JButton();
        f2 = new javax.swing.JButton();
        tu3 = new javax.swing.JButton();
        w3 = new javax.swing.JButton();
        th3 = new javax.swing.JButton();
        f3 = new javax.swing.JButton();
        tu4 = new javax.swing.JButton();
        w4 = new javax.swing.JButton();
        th4 = new javax.swing.JButton();
        f4 = new javax.swing.JButton();
        tu5 = new javax.swing.JButton();
        w5 = new javax.swing.JButton();
        th5 = new javax.swing.JButton();
        f5 = new javax.swing.JButton();
        back = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));
        jPanel1.setPreferredSize(new java.awt.Dimension(668, 393));

        jLabel2.setBackground(new java.awt.Color(255, 51, 51));
        jLabel2.setFont(new java.awt.Font("Rockwell Condensed", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 51));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Hospital Eagle");

        jLabel1.setFont(new java.awt.Font("Rockwell Condensed", 1, 14)); // NOI18N
        jLabel1.setText("MONDAY");

        jLabel3.setFont(new java.awt.Font("Rockwell Condensed", 1, 14)); // NOI18N
        jLabel3.setText("TUESDAY");

        jLabel4.setFont(new java.awt.Font("Rockwell Condensed", 1, 14)); // NOI18N
        jLabel4.setText("WEDNESDAY");

        jLabel5.setFont(new java.awt.Font("Rockwell Condensed", 1, 14)); // NOI18N
        jLabel5.setText("THURSDAY");

        jLabel6.setFont(new java.awt.Font("Rockwell Condensed", 1, 14)); // NOI18N
        jLabel6.setText("FRIDAY");

        m1.setFont(new java.awt.Font("Rockwell Condensed", 1, 14)); // NOI18N
        m1.setText("07.00");
        m1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m1ActionPerformed(evt);
            }
        });

        tu1.setFont(new java.awt.Font("Rockwell Condensed", 1, 14)); // NOI18N
        tu1.setText("07.00");
        tu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tu1ActionPerformed(evt);
            }
        });

        w1.setFont(new java.awt.Font("Rockwell Condensed", 1, 14)); // NOI18N
        w1.setText("07.00");
        w1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                w1ActionPerformed(evt);
            }
        });

        th1.setFont(new java.awt.Font("Rockwell Condensed", 1, 14)); // NOI18N
        th1.setText("07.00");
        th1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                th1ActionPerformed(evt);
            }
        });

        f1.setFont(new java.awt.Font("Rockwell Condensed", 1, 14)); // NOI18N
        f1.setText("07.00");
        f1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f1ActionPerformed(evt);
            }
        });

        m2.setFont(new java.awt.Font("Rockwell Condensed", 1, 14)); // NOI18N
        m2.setText("09.00");
        m2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m2ActionPerformed(evt);
            }
        });

        m3.setFont(new java.awt.Font("Rockwell Condensed", 1, 14)); // NOI18N
        m3.setText("11.00");
        m3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m3ActionPerformed(evt);
            }
        });

        m4.setFont(new java.awt.Font("Rockwell Condensed", 1, 14)); // NOI18N
        m4.setText("13.00");
        m4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m4ActionPerformed(evt);
            }
        });

        m5.setFont(new java.awt.Font("Rockwell Condensed", 1, 14)); // NOI18N
        m5.setText("15.00");
        m5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m5ActionPerformed(evt);
            }
        });

        tu2.setFont(new java.awt.Font("Rockwell Condensed", 1, 14)); // NOI18N
        tu2.setText("09.00");
        tu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tu2ActionPerformed(evt);
            }
        });

        w2.setFont(new java.awt.Font("Rockwell Condensed", 1, 14)); // NOI18N
        w2.setText("09.00");
        w2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                w2ActionPerformed(evt);
            }
        });

        th2.setFont(new java.awt.Font("Rockwell Condensed", 1, 14)); // NOI18N
        th2.setText("09.00");
        th2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                th2ActionPerformed(evt);
            }
        });

        f2.setFont(new java.awt.Font("Rockwell Condensed", 1, 14)); // NOI18N
        f2.setText("09.00");
        f2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f2ActionPerformed(evt);
            }
        });

        tu3.setFont(new java.awt.Font("Rockwell Condensed", 1, 14)); // NOI18N
        tu3.setText("11.00");
        tu3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tu3ActionPerformed(evt);
            }
        });

        w3.setFont(new java.awt.Font("Rockwell Condensed", 1, 14)); // NOI18N
        w3.setText("11.00");
        w3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                w3ActionPerformed(evt);
            }
        });

        th3.setFont(new java.awt.Font("Rockwell Condensed", 1, 14)); // NOI18N
        th3.setText("11.00");
        th3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                th3ActionPerformed(evt);
            }
        });

        f3.setFont(new java.awt.Font("Rockwell Condensed", 1, 14)); // NOI18N
        f3.setText("11.00");
        f3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f3ActionPerformed(evt);
            }
        });

        tu4.setFont(new java.awt.Font("Rockwell Condensed", 1, 14)); // NOI18N
        tu4.setText("13.00");
        tu4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tu4ActionPerformed(evt);
            }
        });

        w4.setFont(new java.awt.Font("Rockwell Condensed", 1, 14)); // NOI18N
        w4.setText("13.00");
        w4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                w4ActionPerformed(evt);
            }
        });

        th4.setFont(new java.awt.Font("Rockwell Condensed", 1, 14)); // NOI18N
        th4.setText("13.00");
        th4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                th4ActionPerformed(evt);
            }
        });

        f4.setFont(new java.awt.Font("Rockwell Condensed", 1, 14)); // NOI18N
        f4.setText("13.00");
        f4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f4ActionPerformed(evt);
            }
        });

        tu5.setFont(new java.awt.Font("Rockwell Condensed", 1, 14)); // NOI18N
        tu5.setText("15.00");
        tu5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tu5ActionPerformed(evt);
            }
        });

        w5.setFont(new java.awt.Font("Rockwell Condensed", 1, 14)); // NOI18N
        w5.setText("15.00");
        w5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                w5ActionPerformed(evt);
            }
        });

        th5.setFont(new java.awt.Font("Rockwell Condensed", 1, 14)); // NOI18N
        th5.setText("15.00");
        th5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                th5ActionPerformed(evt);
            }
        });

        f5.setFont(new java.awt.Font("Rockwell Condensed", 1, 14)); // NOI18N
        f5.setText("15.00");
        f5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f5ActionPerformed(evt);
            }
        });

        back.setBackground(new java.awt.Color(0, 0, 255));
        back.setFont(new java.awt.Font("Rockwell Condensed", 1, 14)); // NOI18N
        back.setText("BACK");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(m5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tu5))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(m4)
                                .addGap(75, 75, 75)
                                .addComponent(tu4))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(m1)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(75, 75, 75)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(tu1)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(m2)
                                .addGap(75, 75, 75)
                                .addComponent(tu2))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(m3)
                                .addGap(75, 75, 75)
                                .addComponent(tu3)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(w1)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(w2)
                            .addComponent(w3)
                            .addComponent(w4)
                            .addComponent(w5))
                        .addGap(61, 61, 61)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(th1)
                                    .addComponent(th2)
                                    .addComponent(th3)
                                    .addComponent(th4)
                                    .addComponent(th5))
                                .addGap(54, 54, 54)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(f1)
                                    .addComponent(f2)
                                    .addComponent(f3)
                                    .addComponent(f4)
                                    .addComponent(f5)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(64, 64, 64)
                                .addComponent(jLabel6)))
                        .addGap(49, 49, 49))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(back)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(back)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(m1)
                    .addComponent(tu1)
                    .addComponent(w1)
                    .addComponent(th1)
                    .addComponent(f1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(m2)
                    .addComponent(tu2)
                    .addComponent(w2)
                    .addComponent(th2)
                    .addComponent(f2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(m3)
                    .addComponent(tu3)
                    .addComponent(w3)
                    .addComponent(th3)
                    .addComponent(f3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(m4)
                    .addComponent(tu4)
                    .addComponent(w4)
                    .addComponent(th4)
                    .addComponent(f4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(m5)
                    .addComponent(tu5)
                    .addComponent(w5)
                    .addComponent(th5)
                    .addComponent(f5))
                .addContainerGap(139, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 669, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void m1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m1ActionPerformed
        // TODO add your handling code here:
        dname = op.selectDName(this.connector);
   
        String sch = op.takeSchedule(dname);
        if(sch.substring(0,1).equals("0")){
            String newSch = "1"+sch.substring(1);
            op.takeTime(dname, newSch);
            op.sendSchedule(newSch,dname);
            m1.setBackground(Color.red);
        }
        if(sch.substring(0,1).equals("1")){
            String newSch = "0"+sch.substring(1);
            op.takeTime(dname, newSch);
            op.sendSchedule(newSch,dname);
            m1.setBackground(Color.white);
        }
    }//GEN-LAST:event_m1ActionPerformed

    private void tu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tu1ActionPerformed
        // TODO add your handling code here:
        dname = op.selectDName(this.connector);
        String sch = op.takeSchedule(dname);

        if(sch.charAt(5)=='0'){
            String newSch = sch.substring(0,5)+"1"+sch.substring(6);
            op.takeTime(dname, newSch);
            op.sendSchedule(newSch,dname);
            tu1.setBackground(Color.red);
        }
        if(sch.charAt(5)=='1'){
            String newSch = sch.substring(0,5)+"0"+sch.substring(6);
            op.takeTime(dname, newSch);
            op.sendSchedule(newSch,dname);
            tu1.setBackground(Color.white);
        }
    }//GEN-LAST:event_tu1ActionPerformed

    private void w1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_w1ActionPerformed
        // TODO add your handling code here:
        dname = op.selectDName(this.connector);
        String sch = op.takeSchedule(dname);

        if(sch.charAt(10)=='0'){
            String newSch = sch.substring(0,10)+"1"+sch.substring(11);
            op.takeTime(dname, newSch);
            op.sendSchedule(newSch,dname);
            w1.setBackground(Color.red);
        }
        if(sch.charAt(10)=='1'){
            String newSch = sch.substring(0,10)+"0"+sch.substring(11);
            op.takeTime(dname, newSch);
            op.sendSchedule(newSch,dname);
            w1.setBackground(Color.white);
        }
    }//GEN-LAST:event_w1ActionPerformed

    private void th1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_th1ActionPerformed
        // TODO add your handling code here:
        dname = op.selectDName(this.connector);
        String sch = op.takeSchedule(dname);

        if(sch.charAt(15)=='0'){
            String newSch = sch.substring(0,15)+"1"+sch.substring(16);
            op.takeTime(dname, newSch);
            op.sendSchedule(newSch,dname);
            th1.setBackground(Color.red);
        }
        if(sch.charAt(15)=='1'){
            String newSch = sch.substring(0,15)+"0"+sch.substring(16);
            op.takeTime(dname, newSch);
            op.sendSchedule(newSch,dname);
            th1.setBackground(Color.white);
        }
    }//GEN-LAST:event_th1ActionPerformed

    private void f1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f1ActionPerformed
        // TODO add your handling code here:
        dname = op.selectDName(this.connector);
        String sch = op.takeSchedule(dname);

        if(sch.charAt(20)=='0'){
            String newSch = sch.substring(0,20)+"1"+sch.substring(21);
            op.takeTime(dname, newSch);
            op.sendSchedule(newSch,dname);
            f1.setBackground(Color.red);
        }
        else if(sch.charAt(20)=='1'){
            String newSch = sch.substring(0,20)+"0"+sch.substring(21);
            op.takeTime(dname, newSch);
            op.sendSchedule(newSch,dname);
            f1.setBackground(Color.white);
        }
    }//GEN-LAST:event_f1ActionPerformed

    private void m2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m2ActionPerformed
        // TODO add your handling code here:
        dname = op.selectDName(this.connector);
        String sch = op.takeSchedule(dname);

        if(sch.substring(1,2).equals("0")){
            String newSch = sch.substring(1,2)+"1"+sch.substring(2);
            op.takeTime(dname, newSch);
            op.sendSchedule(newSch,dname);
            m2.setBackground(Color.red);
        }
        if(sch.substring(1,2).equals("1")){
            String newSch = sch.substring(1,2)+"0"+sch.substring(2);
            op.takeTime(dname, newSch);
            op.sendSchedule(newSch,dname);
            m2.setBackground(Color.white);
        }
    }//GEN-LAST:event_m2ActionPerformed

    private void m3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m3ActionPerformed
        // TODO add your handling code here:
        dname = op.selectDName(this.connector);
        String sch = op.takeSchedule(dname);

        if(sch.charAt(2)=='0'){
            String newSch = sch.substring(0,2)+"1"+sch.substring(3);
            op.takeTime(dname, newSch);
            op.sendSchedule(newSch,dname);
            m3.setBackground(Color.red);
        }
        if(sch.charAt(2)=='1'){
            String newSch = sch.substring(0,2)+"0"+sch.substring(3);
            op.takeTime(dname, newSch);
            op.sendSchedule(newSch,dname);
            m3.setBackground(Color.white);
        }
    }//GEN-LAST:event_m3ActionPerformed

    private void m4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m4ActionPerformed
        // TODO add your handling code here:
        dname = op.selectDName(this.connector);
        String sch = op.takeSchedule(dname);

        if(sch.charAt(3)=='0'){
            String newSch = sch.substring(0,3)+"1"+sch.substring(4);
            op.takeTime(dname, newSch);
            op.sendSchedule(newSch,dname);
            m4.setBackground(Color.red);
        }
        if(sch.charAt(3)=='1'){
            String newSch = sch.substring(0,3)+"0"+sch.substring(4);
            op.takeTime(dname, newSch);
            op.sendSchedule(newSch,dname);
            m4.setBackground(Color.white);
        }
    }//GEN-LAST:event_m4ActionPerformed

    private void m5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m5ActionPerformed
        // TODO add your handling code here:
        dname = op.selectDName(this.connector);
        String sch = op.takeSchedule(dname);

        if(sch.charAt(4)=='0'){
            String newSch = sch.substring(0,4)+"1"+sch.substring(5);
            op.takeTime(dname, newSch);
            op.sendSchedule(newSch,dname);
            m5.setBackground(Color.red);
        }
        if(sch.charAt(4)=='1'){
            String newSch = sch.substring(0,4)+"0"+sch.substring(5);
            op.takeTime(dname, newSch);
            op.sendSchedule(newSch,dname);
            m5.setBackground(Color.white);
        }
    }//GEN-LAST:event_m5ActionPerformed

    private void tu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tu2ActionPerformed
        // TODO add your handling code here:
        dname = op.selectDName(this.connector);
        String sch = op.takeSchedule(dname);

        if(sch.charAt(6)=='0'){
            String newSch = sch.substring(0,6)+"1"+sch.substring(7);
            op.takeTime(dname, newSch);
            op.sendSchedule(newSch,dname);
            tu2.setBackground(Color.red);
        }
        if(sch.charAt(6)=='1'){
            String newSch = sch.substring(0,6)+"0"+sch.substring(7);
            op.takeTime(dname, newSch);
            op.sendSchedule(newSch,dname);
            tu2.setBackground(Color.white);
        }
        
    }//GEN-LAST:event_tu2ActionPerformed

    private void w2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_w2ActionPerformed
        // TODO add your handling code here:
        dname = op.selectDName(this.connector);
        String sch = op.takeSchedule(dname);

        if(sch.charAt(11)=='0'){
            String newSch = sch.substring(0,11)+"1"+sch.substring(12);
            op.takeTime(dname, newSch);
            op.sendSchedule(newSch,dname);
            w2.setBackground(Color.white);
        }
        if(sch.charAt(11)=='1'){
            String newSch = sch.substring(0,11)+"0"+sch.substring(12);
            op.takeTime(dname, newSch);
            op.sendSchedule(newSch,dname);
            w2.setBackground(Color.white);
        }
    }//GEN-LAST:event_w2ActionPerformed

    private void th2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_th2ActionPerformed
        // TODO add your handling code here:
        dname = op.selectDName(this.connector);
        String sch = op.takeSchedule(dname);

        if(sch.charAt(16)=='0'){
            String newSch = sch.substring(0,16)+"1"+sch.substring(17);
            op.takeTime(dname, newSch);
            op.sendSchedule(newSch,dname);
            th2.setBackground(Color.red);
        }
        if(sch.charAt(16)=='1'){
            String newSch = sch.substring(0,16)+"0"+sch.substring(17);
            op.takeTime(dname, newSch);
            op.sendSchedule(newSch,dname);
            th2.setBackground(Color.white);
        }
    }//GEN-LAST:event_th2ActionPerformed

    private void f2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f2ActionPerformed
        // TODO add your handling code here:
        dname = op.selectDName(this.connector);
        String sch = op.takeSchedule(dname);

        if(sch.charAt(21)=='0'){
            String newSch = sch.substring(0,21)+"1"+sch.substring(22);
            op.takeTime(dname, newSch);
            op.sendSchedule(newSch,dname);
            f2.setBackground(Color.red);
        }
        if(sch.charAt(21)=='1'){
            String newSch = sch.substring(0,21)+"0"+sch.substring(22);
            op.takeTime(dname, newSch);
            op.sendSchedule(newSch,dname);
            f2.setBackground(Color.white);
        }
    }//GEN-LAST:event_f2ActionPerformed

    private void tu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tu3ActionPerformed
        // TODO add your handling code here:
        dname = op.selectDName(this.connector);
        String sch = op.takeSchedule(dname);

        if(sch.charAt(7)=='0'){
            String newSch = sch.substring(0,7)+"1"+sch.substring(8);
            op.takeTime(dname, newSch);
            op.sendSchedule(newSch,dname);
            tu3.setBackground(Color.red);
        }
         if(sch.charAt(7)=='1'){
            String newSch = sch.substring(0,7)+"0"+sch.substring(8);
            op.takeTime(dname, newSch);
            op.sendSchedule(newSch,dname);
            tu3.setBackground(Color.white);
        }
    }//GEN-LAST:event_tu3ActionPerformed

    private void w3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_w3ActionPerformed
        // TODO add your handling code here:
        dname = op.selectDName(this.connector);
        String sch = op.takeSchedule(dname);

        if(sch.charAt(12)=='0'){
            String newSch = sch.substring(0,12)+"1"+sch.substring(13);
            op.takeTime(dname, newSch);
            op.sendSchedule(newSch,dname);
            w3.setBackground(Color.red);
        }
        if(sch.charAt(12)=='1'){
            String newSch = sch.substring(0,12)+"0"+sch.substring(13);
            op.takeTime(dname, newSch);
            op.sendSchedule(newSch,dname);
            w3.setBackground(Color.white);
        }
    }//GEN-LAST:event_w3ActionPerformed

    private void th3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_th3ActionPerformed
        // TODO add your handling code here:
        dname = op.selectDName(this.connector);
        String sch = op.takeSchedule(dname);

        if(sch.charAt(17)=='0'){
            String newSch = sch.substring(0,17)+"1"+sch.substring(18);
            op.takeTime(dname, newSch);
            op.sendSchedule(newSch,dname);
            th3.setBackground(Color.red);
        }
        if(sch.charAt(17)=='1'){
            String newSch = sch.substring(0,17)+"0"+sch.substring(18);
            op.takeTime(dname, newSch);
            op.sendSchedule(newSch,dname);
            th3.setBackground(Color.white);
        }
    }//GEN-LAST:event_th3ActionPerformed

    private void f3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f3ActionPerformed
        // TODO add your handling code here:
        dname = op.selectDName(this.connector);
        String sch = op.takeSchedule(dname);

        if(sch.charAt(22)=='0'){
            String newSch = sch.substring(0,22)+"1"+sch.substring(23);
            op.takeTime(dname, newSch);
            op.sendSchedule(newSch,dname);
            f3.setBackground(Color.red);
        }
        if(sch.charAt(22)=='1'){
            String newSch = sch.substring(0,22)+"0"+sch.substring(23);
            op.takeTime(dname, newSch);
            op.sendSchedule(newSch,dname);
            f3.setBackground(Color.white);
        }
    }//GEN-LAST:event_f3ActionPerformed

    private void tu4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tu4ActionPerformed
        // TODO add your handling code here:
        dname = op.selectDName(this.connector);
        String sch = op.takeSchedule(dname);

        if(sch.charAt(8)=='0'){
            String newSch = sch.substring(0,8)+"1"+sch.substring(9);
            op.takeTime(dname, newSch);
            op.sendSchedule(newSch,dname);
            tu4.setBackground(Color.red);
        }
        if(sch.charAt(8)=='1'){
            String newSch = sch.substring(0,8)+"0"+sch.substring(9);
            op.takeTime(dname, newSch);
            op.sendSchedule(newSch,dname);
            tu4.setBackground(Color.white);
        }
    }//GEN-LAST:event_tu4ActionPerformed

    private void w4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_w4ActionPerformed
        // TODO add your handling code here:
        dname = op.selectDName(this.connector);
        String sch = op.takeSchedule(dname);

        if(sch.charAt(13)=='0'){
            String newSch = sch.substring(0,13)+"1"+sch.substring(14);
            op.takeTime(dname, newSch);
            op.sendSchedule(newSch,dname);
            w4.setBackground(Color.red);
        }
        if(sch.charAt(13)=='1'){
            String newSch = sch.substring(0,13)+"0"+sch.substring(14);
            op.takeTime(dname, newSch);
            op.sendSchedule(newSch,dname);
            w4.setBackground(Color.white);
        }
    }//GEN-LAST:event_w4ActionPerformed

    private void th4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_th4ActionPerformed
        // TODO add your handling code here:
        dname = op.selectDName(this.connector);
        String sch = op.takeSchedule(dname);

        if(sch.charAt(18)=='0'){
            String newSch = sch.substring(0,18)+"1"+sch.substring(19);
            op.takeTime(dname, newSch);
            op.sendSchedule(newSch,dname);
            th4.setBackground(Color.red);
        }
        if(sch.charAt(18)=='1'){
            String newSch = sch.substring(0,18)+"0"+sch.substring(19);
            op.takeTime(dname, newSch);
            op.sendSchedule(newSch,dname);
            th4.setBackground(Color.white);
        }
    }//GEN-LAST:event_th4ActionPerformed

    private void f4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f4ActionPerformed
        // TODO add your handling code here:
        dname = op.selectDName(this.connector);
        String sch = op.takeSchedule(dname);

        if(sch.charAt(23)=='0'){
            String newSch = sch.substring(0,23)+"1"+sch.substring(24);
            op.takeTime(dname, newSch);
            op.sendSchedule(newSch,dname);
            f4.setBackground(Color.red);
        }
        if(sch.charAt(23)=='1'){
            String newSch = sch.substring(0,23)+"0"+sch.substring(24);
            op.takeTime(dname, newSch);
            op.sendSchedule(newSch,dname);
            f4.setBackground(Color.white);
        }
    }//GEN-LAST:event_f4ActionPerformed

    private void tu5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tu5ActionPerformed
        // TODO add your handling code here:
        dname = op.selectDName(this.connector);
        String sch = op.takeSchedule(dname);

        if(sch.charAt(9)=='0'){
            String newSch = sch.substring(0,9)+"1"+sch.substring(10);
            op.takeTime(dname, newSch);
            op.sendSchedule(newSch,dname);
            tu5.setBackground(Color.red);
        }
        if(sch.charAt(9)=='1'){
            String newSch = sch.substring(0,9)+"0"+sch.substring(10);
            op.takeTime(dname, newSch);
            op.sendSchedule(newSch,dname);
            tu5.setBackground(Color.white);
        }
    }//GEN-LAST:event_tu5ActionPerformed

    private void w5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_w5ActionPerformed
        // TODO add your handling code here:
        dname = op.selectDName(this.connector);
        String sch = op.takeSchedule(dname);

        if(sch.charAt(14)=='0'){
            String newSch = sch.substring(0,14)+"1"+sch.substring(15);
            op.takeTime(dname, newSch);
            op.sendSchedule(newSch,dname);
            w5.setBackground(Color.red);
        }
        if(sch.charAt(14)=='1'){
            String newSch = sch.substring(0,14)+"0"+sch.substring(15);
            op.takeTime(dname, newSch);
            op.sendSchedule(newSch,dname);
            w5.setBackground(Color.white);
        }
    }//GEN-LAST:event_w5ActionPerformed

    private void th5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_th5ActionPerformed
        // TODO add your handling code here:
        dname = op.selectDName(this.connector);
        String sch = op.takeSchedule(dname);

        if(sch.charAt(19)=='0'){
            String newSch = sch.substring(0,19)+"1"+sch.substring(20);
            op.takeTime(dname, newSch);
            op.sendSchedule(newSch,dname);
            th5.setBackground(Color.red);
        }
        if(sch.charAt(19)=='1'){
            String newSch = sch.substring(0,19)+"0"+sch.substring(20);
            op.takeTime(dname, newSch);
            op.sendSchedule(newSch,dname);
            th5.setBackground(Color.white);
        }
    }//GEN-LAST:event_th5ActionPerformed

    private void f5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f5ActionPerformed
        // TODO add your handling code here:
        dname = op.selectDName(this.connector);
        String sch = op.takeSchedule(dname);

        if(sch.charAt(24)=='0'){
            String newSch = sch.substring(0,24)+"1";
            op.takeTime(dname, newSch);
            op.sendSchedule(newSch,dname);
            f5.setBackground(Color.red);
        }
        if(sch.charAt(24)=='1'){
            String newSch = sch.substring(0,24)+"0";
            op.takeTime(dname, newSch);
            op.sendSchedule(newSch,dname);
            f5.setBackground(Color.white);
        }
        
    }//GEN-LAST:event_f5ActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        MainScreenForDoctors ds = new MainScreenForDoctors();
        ds.connector = this.connector;
        ds.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_backActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(editSchForDoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(editSchForDoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(editSchForDoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(editSchForDoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new editSchForDoc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JButton f1;
    private javax.swing.JButton f2;
    private javax.swing.JButton f3;
    private javax.swing.JButton f4;
    private javax.swing.JButton f5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton m1;
    private javax.swing.JButton m2;
    private javax.swing.JButton m3;
    private javax.swing.JButton m4;
    private javax.swing.JButton m5;
    private javax.swing.JButton th1;
    private javax.swing.JButton th2;
    private javax.swing.JButton th3;
    private javax.swing.JButton th4;
    private javax.swing.JButton th5;
    private javax.swing.JButton tu1;
    private javax.swing.JButton tu2;
    private javax.swing.JButton tu3;
    private javax.swing.JButton tu4;
    private javax.swing.JButton tu5;
    private javax.swing.JButton w1;
    private javax.swing.JButton w2;
    private javax.swing.JButton w3;
    private javax.swing.JButton w4;
    private javax.swing.JButton w5;
    // End of variables declaration//GEN-END:variables
}
